### PR TITLE
Add Bluespace Reactor Cell, and Cargo Buffs

### PR DESCRIPTION
**Pull request by MitztheKat**
## About The Pull Request
Bluespace reactor cell. Slime cell, but weaker and craftable.
Cargo buffs and Mineral sample crate.

## Why It's Good For The Game
Mining as AI is bad.
Cargo needs some love and attention.
Borgs love bluespace reactor cells, trust me :3

## Changelog
:cl:
add: Added the mineral sample crate, when mining does not exist.
add: Added bluespace reactor cell. Borgs love it!
balance: buffed cargo to high heavens.
/:cl:

### CODE REVIEW

**Comment by MitztheKat** [comment]
tested. Just putting this here for review.

**Comment by faaaay** [comment]
To be sure I'm reading this correctly - does this crate include bananium and abductor alloy?

Also, I see there are a couple of changes to crafting and item names in the files. While the code is okay, please may you let me know what exactly the PR does?

**Comment by Guidesu** [comment]
Looks fine code-wise

**Comment by MitztheKat** [comment]
Well:
I added in the crafting recipe for reactor cells,
I added in different sized stacks for materials for the mat sample crate,
I changed a lot of export prices referring to a skyrat PR,
and NO it does not contain bananium but YES it contains abductor alloy. Bananium is too dangerous and is obtainable any shift with xenobio.

**Comment by faaaay** [comment]
> 
> 
> Well:
> I added in the crafting recipe for reactor cells,
> I added in different sized stacks for materials for the mat sample crate,
> I changed a lot of export prices referring to a skyrat PR,
> and NO it does not contain bananium but YES it contains abductor alloy. Bananium is too dangerous and is obtainable any shift with xenobio.

Right, thanks! 
In a vacuum, I think it may be a little strong, but as our current population is usually fairly low I think it's pretty reasonable to add these buffs.

+1 from me. (Not sure what it's +1 _of_, but +1.)

**Comment by MitztheKat** [comment]
Seems like i've got enough headcoder approval

**Pull request merged**
